package com.example.dblib.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dblib.bean.FilePath;

import com.example.dblib.greendao.FilePathDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig filePathDaoConfig;

    private final FilePathDao filePathDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        filePathDaoConfig = daoConfigMap.get(FilePathDao.class).clone();
        filePathDaoConfig.initIdentityScope(type);

        filePathDao = new FilePathDao(filePathDaoConfig, this);

        registerDao(FilePath.class, filePathDao);
    }
    
    public void clear() {
        filePathDaoConfig.clearIdentityScope();
    }

    public FilePathDao getFilePathDao() {
        return filePathDao;
    }

}
